version: '3'

services:
  fhir:
    build:
      context: fhir
      dockerfile: Dockerfile
    env_file:
      - .local-secrets/auth.secrets
    environment:
      SERVER_PORT: 3000
      RESOURCE_SERVER: http://myserver.com
      AUTH_SERVER_URI: https://afternoon-springs-39948.herokuapp.com/
      # SSL_KEY: ./src/key.pem
      # SSL_CERT: ./src/cert.pem
    ports:
      - "3000:3000"
    volumes:
      - ./fhir/scripts:/srv/src/scripts
      - ./.eslintrc:/srv/src/.eslintrc
      - ./fhir/src:/srv/src/src
<<<<<<< HEAD
    command: yarn nodemon
=======
    command: yarn nodemon

  mongo:
    image: mongo:3.6.1
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
>>>>>>> feature/more-test-coverage
